"""
Seed destinations for the VenturePath inspire scraper.
Each entry drives one Wikipedia fetch + one Overpass POI query.
"""

DESTINATIONS = [
    # Asia
    {
        "id": "kyoto",
        "name": "Kyoto",
        "country": "Japan",
        "continent": "Asia",
        "tags": ["cultural", "temples", "food", "traditional", "gardens"],
        "wikipedia_title": "Kyoto",
        "overpass_bbox": [34.9, 135.6, 35.1, 135.9],  # [south, west, north, east]
    },
    {
        "id": "chiang-mai",
        "name": "Chiang Mai",
        "country": "Thailand",
        "continent": "Asia",
        "tags": ["temples", "food", "trekking", "elephants", "night-market"],
        "wikipedia_title": "Chiang Mai",
        "overpass_bbox": [18.7, 98.9, 18.9, 99.1],
    },
    {
        "id": "hanoi",
        "name": "Hanoi",
        "country": "Vietnam",
        "continent": "Asia",
        "tags": ["street-food", "old-quarter", "lakes", "colonial", "coffee"],
        "wikipedia_title": "Hanoi",
        "overpass_bbox": [21.0, 105.8, 21.1, 105.9],
    },
    {
        "id": "bali-ubud",
        "name": "Ubud",
        "country": "Indonesia",
        "continent": "Asia",
        "tags": ["rice-terraces", "temples", "wellness", "art", "jungle"],
        "wikipedia_title": "Ubud",
        "overpass_bbox": [-8.6, 115.2, -8.4, 115.4],
    },
    {
        "id": "tbilisi",
        "name": "Tbilisi",
        "country": "Georgia",
        "continent": "Asia",
        "tags": ["wine", "architecture", "baths", "caucasus", "food"],
        "wikipedia_title": "Tbilisi",
        "overpass_bbox": [41.6, 44.7, 41.8, 45.0],
    },
    {
        "id": "kathmandu",
        "name": "Kathmandu",
        "country": "Nepal",
        "continent": "Asia",
        "tags": ["temples", "himalaya", "trekking", "culture", "markets"],
        "wikipedia_title": "Kathmandu",
        "overpass_bbox": [27.6, 85.2, 27.8, 85.4],
    },
    {
        "id": "istanbul",
        "name": "Istanbul",
        "country": "Turkey",
        "continent": "Asia",
        "tags": ["mosques", "bazaars", "bosphorus", "food", "history"],
        "wikipedia_title": "Istanbul",
        "overpass_bbox": [41.0, 28.9, 41.1, 29.1],
    },

    # Europe
    {
        "id": "lisbon",
        "name": "Lisbon",
        "country": "Portugal",
        "continent": "Europe",
        "tags": ["coastal", "tram", "food", "fado", "architecture"],
        "wikipedia_title": "Lisbon",
        "overpass_bbox": [38.7, -9.2, 38.8, -9.1],
    },
    {
        "id": "sarajevo",
        "name": "Sarajevo",
        "country": "Bosnia and Herzegovina",
        "continent": "Europe",
        "tags": ["history", "coffee", "balkans", "war", "architecture"],
        "wikipedia_title": "Sarajevo",
        "overpass_bbox": [43.8, 18.3, 43.9, 18.5],
    },
    {
        "id": "dubrovnik",
        "name": "Dubrovnik",
        "country": "Croatia",
        "continent": "Europe",
        "tags": ["walled-city", "adriatic", "islands", "coastal", "medieval"],
        "wikipedia_title": "Dubrovnik",
        "overpass_bbox": [42.6, 18.0, 42.7, 18.2],
    },
    {
        "id": "edinburgh",
        "name": "Edinburgh",
        "country": "Scotland",
        "continent": "Europe",
        "tags": ["castle", "whisky", "festivals", "architecture", "highlands"],
        "wikipedia_title": "Edinburgh",
        "overpass_bbox": [55.9, -3.3, 56.0, -3.1],
    },
    {
        "id": "porto",
        "name": "Porto",
        "country": "Portugal",
        "continent": "Europe",
        "tags": ["wine", "azulejos", "river", "food", "architecture"],
        "wikipedia_title": "Porto",
        "overpass_bbox": [41.1, -8.7, 41.2, -8.5],
    },
    {
        "id": "kotor",
        "name": "Kotor",
        "country": "Montenegro",
        "continent": "Europe",
        "tags": ["bay", "medieval", "walls", "cats", "adriatic"],
        "wikipedia_title": "Kotor",
        "overpass_bbox": [42.4, 18.7, 42.5, 18.8],
    },

    # Africa & Middle East
    {
        "id": "marrakech",
        "name": "Marrakech",
        "country": "Morocco",
        "continent": "Africa",
        "tags": ["medina", "souks", "food", "desert", "culture"],
        "wikipedia_title": "Marrakesh",
        "overpass_bbox": [31.6, -8.1, 31.7, -7.9],
    },
    {
        "id": "fes",
        "name": "Fes",
        "country": "Morocco",
        "continent": "Africa",
        "tags": ["medina", "tanneries", "medieval", "souks", "islamic"],
        "wikipedia_title": "Fez, Morocco",
        "overpass_bbox": [34.0, -5.1, 34.1, -4.9],
    },
    {
        "id": "cape-town",
        "name": "Cape Town",
        "country": "South Africa",
        "continent": "Africa",
        "tags": ["mountains", "wine", "beaches", "penguins", "coastal"],
        "wikipedia_title": "Cape Town",
        "overpass_bbox": [-34.0, 18.4, -33.8, 18.6],
    },

    # Americas
    {
        "id": "oaxaca",
        "name": "Oaxaca",
        "country": "Mexico",
        "continent": "Americas",
        "tags": ["food", "mezcal", "markets", "indigenous", "ruins"],
        "wikipedia_title": "Oaxaca City",
        "overpass_bbox": [17.0, -96.8, 17.1, -96.6],
    },
    {
        "id": "cartagena",
        "name": "Cartagena",
        "country": "Colombia",
        "continent": "Americas",
        "tags": ["colonial", "beaches", "food", "walled city", "caribbean"],
        "wikipedia_title": "Cartagena, Colombia",
        "overpass_bbox": [10.4, -75.6, 10.5, -75.4],
    },
    {
        "id": "medellin",
        "name": "Medellín",
        "country": "Colombia",
        "continent": "Americas",
        "tags": ["transformation", "cable-car", "flowers", "coffee", "nightlife"],
        "wikipedia_title": "Medellín",
        "overpass_bbox": [6.2, -75.6, 6.3, -75.5],
    },
    {
        "id": "cusco",
        "name": "Cusco",
        "country": "Peru",
        "continent": "Americas",
        "tags": ["inca", "altitude", "history", "markets", "gateway"],
        "wikipedia_title": "Cusco",
        "overpass_bbox": [-13.6, -72.0, -13.4, -71.8],
    },
    {
        "id": "buenos-aires",
        "name": "Buenos Aires",
        "country": "Argentina",
        "continent": "Americas",
        "tags": ["tango", "steak", "architecture", "nightlife", "culture"],
        "wikipedia_title": "Buenos Aires",
        "overpass_bbox": [-34.7, -58.5, -34.5, -58.3],
    },
    {
        "id": "san-cristobal",
        "name": "San Cristóbal de las Casas",
        "country": "Mexico",
        "continent": "Americas",
        "tags": ["indigenous", "colonial", "highlands", "markets", "coffee"],
        "wikipedia_title": "San Cristóbal de las Casas",
        "overpass_bbox": [16.7, -92.7, 16.8, -92.6],
    },

    # Oceania
    {
        "id": "luang-prabang",
        "name": "Luang Prabang",
        "country": "Laos",
        "continent": "Asia",
        "tags": ["monks", "waterfalls", "mekong", "temples", "slow-travel"],
        "wikipedia_title": "Luang Prabang",
        "overpass_bbox": [19.8, 102.1, 19.9, 102.2],
    },
]
